### ISSUE TITLE
Unable to get Flakiness Reporter working

### ISSUE THREAD

**Issue by rkochhar** [shazam/fork#105] opened 2017-05-21 15:45 UTC
The example configuration below seems to be outdated - 
```
forkJenkins {
    reportTitle = "My project's awesome flakiness report"
    jenkinsUrl = "http://my-jenkins.server.net:8080/"
    jenkinsJobName = "Master"
    jenkinsReportTitle = "Fork Report"
 }
```

I had to add `jenkinsUsername, jenkinsPassword, freestyleJob` to configuration.
After that, `forkJenkinsReport` tasks fails as it is unable to get artifact from the other job running fork-tests. 

My configuration looks like this - 
```
forkJenkins { 
        reportTitle = "My project's awesome flakiness report"
        jenkinsUrl = "<jenkins-url>"
        jenkinsUsername = "userName"
        jenkinsPassword = '****'
        jenkinsReportTitle = "Fork Report"
        freestyleJob {
            jobName = "UITests-Flaky-Test"
        }
    }
```

Error message seen : 
```
11:14:31.566 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :project:forkJenkinsReport (Thread[Task worker,5,main]) completed. Took 6.04 secs.
11:14:31.566 [DEBUG] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] Task worker [Thread[Task worker,5,main]] finished, busy: 6.04 secs, idle: 0.001 secs
11:14:31.575 [ERROR] [org.gradle.BuildExceptionReporter] 
11:14:31.578 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
11:14:31.578 [ERROR] [org.gradle.BuildExceptionReporter] 
11:14:31.578 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
11:14:31.578 [ERROR] [org.gradle.BuildExceptionReporter] Execution failed for task ':project:forkJenkinsReport'.
11:14:31.578 [ERROR] [org.gradle.BuildExceptionReporter] > Could not download artifact from: https://<jenkins>/job/UITests-Flaky-Test/5/artifact/project/build/fork/expedia/debug/summary/fork-1495377845068.json?#
11:14:31.579 [ERROR] [org.gradle.BuildExceptionReporter] 
11:14:31.579 [ERROR] [org.gradle.BuildExceptionReporter] * Exception is:
11:14:31.579 [ERROR] [org.gradle.BuildExceptionReporter] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':project:forkJenkinsReport'.
11:14:31.580 [ERROR] [org.gradle.BuildExceptionReporter] 	at
```
Has someone come across this while using Flakyness Reporter?

**Comment by iordanis** [comment] 2017-05-22 13:16
Can you check if this `https://<jenkins>/job/UITests-Flaky-Test/5/artifact/project/build/fork/expedia/debug/summary/fork-1495377845068.json?#` exists?

**Comment by rkochhar** [comment] 2017-05-22 14:31
Yes it does. I was able to open the same in a browser.

**Comment by iordanis** [comment] 2017-05-23 10:38
I'll try to reproduce. In the meantime, can you confirm which version you've been using?

**Comment by iordanis** [comment] 2017-05-23 12:12
I have created a project with similar setup but unfortunately I can't reproduce the issue. To help track down the bug:
- make sure you have the build script dependency: "com.shazam.fork:fork-reporter-jenkins-gradle-plugin:2.2.0-SNAPSHOT"
- clone the `master` branch of https://github.com/shazam/fork
- edit your `~/.gradle/gradle.properties` to have a line with: `org.gradle.jvmargs=-Xdebug -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5005`
- add a breakpoint somewhere in the reporter project. A good start is `com.shazam.fork.reporter.gradle.ForkJenkinsReportTask.runForkJenkins()`
- attach your debugger to the agent. In Intellij/Android Studio go to: `Edit Configurations...` > Select `Defaults` > Press `+` on top left > Choose `Remote`. Add a name for the configuration and press OK > Press the `Debug` button.

You should now be able to debug the plugin run. 

Hope that helps.

**Comment by rkochhar** [comment] 2017-05-28 06:42
@iordanis I tried debugging. Getting an error in downloadArtifact method (line - `asByteSource(artifactUrl).copyTo(output);`):
```private void downloadArtifact(Build build, Artifact artifact) {
        FileOutputStream output = null;
        URL artifactUrl = getArtifactUrl(build, artifact);
        try {
            File summaryFile = new File(forkSummariesDir, format(FORK_SUMMARY_FILENAME_FORMAT, build.getNumber()));
            output = new FileOutputStream(summaryFile);
            asByteSource(artifactUrl).copyTo(output);
        } catch (IOException e) {
            throw new GradleException("Could not download artifact from: " + artifactUrl.toString(), e);
        } finally {
            closeQuietly(output);
        }
    }
```
Don't we need to provide authentication while downloading artifacts as we do while fetching job details?

**Comment by iordanis** [comment] 2017-05-28 12:00
Good point. That can be achieved by using `JenkinsHttpClient.getFile()`, which seems to offer authenticated access to resources. 

The only code change then would be to create `JenkinsServer` with the constructor that takes that pre-existing client instance `JenkinsServer(client)`.

**Comment by rkochhar** [comment] 2017-05-29 05:42
@iordanis Please have a look at this : https://github.com/shazam/fork/pull/108

**Comment by iordanis** [comment] 2017-05-29 16:39
#108 Merged. Snapshot with the fix has been deployed, so closing.

Thanks, @rkochhar!

**Comment by edwardharks** [comment] 2017-05-30 15:36
This change is causing issues for us. In `JenkinsDownloader` the method `getDetailsFromBuild` never returns and therefore the build never completes. 

Interestingly the first 2 times this is called it works fine and always on the 3rd call, the method never returns.

**Comment by edwardharks** [comment] 2017-05-31 10:39
Opened PR - #109. The issue was that the input stream used to download the artifact was not being closed

**Closed** 2017-05-31 11:18 UTC
Labels: bug
